### ISSUE TITLE
Support static TLS wildcards in net-contour

### ISSUE THREAD

**Issue by mattmoor** [knative-sandbox/net-contour#182]
Ideally we'd have a story similar to [this](https://knative.dev/docs/serving/using-a-tls-cert/#manually-adding-a-tls-certificate) for Contour.

**Comment by mattmoor** [comment]
One option would be to support identifying a static certificate in config-contour to fallback on when no TLS certificate is specified.

**Comment by jpeach** [comment]
I think that if possible, it would be preferable for net-contour to support [auto-TLS](https://knative.dev/docs/serving/using-auto-tls/) for Knative Services. Watch out for using wildcard certificates with HTTP/2 (see the Contour 421 [FAQ](https://projectcontour.io/resources/faq/).

**Comment by mattmoor** [comment]
@jpeach it already supports auto-TLS with various cert provisioning schemes.  This is specifically around byo-certificates in the knative use case.

**Comment by almottier** [comment]
Would be much appreciated. That's the feature we are missing to switch from Istio.

**Comment by mattmoor** [comment]
/assign @dprotaso 

Dave said he'd take a look 🥳
