### ISSUE TITLE
Ensure the TLS min version is 1.2

### ISSUE THREAD

**Issue by dprotaso** [knative-sandbox/net-contour#188]
The default is 1.1 which is deprecated & insecure

Details: https://github.com/projectcontour/contour/issues/2777

/kind good-first-issue

**Comment by mattmoor** [comment]
@tcnghia do we have any broader guidance here around compatibility?

**Comment by guacamole** [comment]
Hey @mattmoor , can i give it a shot?

**Comment by dprotaso** [comment]
Awesome yeah!

/assign @guacamole

**Comment by guacamole** [comment]
@dprotaso just wanted to make sure the repo to fork will be  projectcontour /contour and not  knative-sandbox /net-contour

**Comment by guacamole** [comment]
@dprotaso Also, if i should remove the deprecation warning set by #2777 ?

**Comment by dprotaso** [comment]
@guacamole hey - this issue is for setting the default in this repository since some installations could be running older contours where it defaults to TLS 1.1

**Comment by dprotaso** [comment]
> @dprotaso Also, if i should remove the deprecation warning set by #2777 ?

I'd reach out to the contour folks for any of the upstream work

**Comment by mattmoor** [comment]
/lifecycle frozen

Ping @dprotaso

**Comment by dprotaso** [comment]
Looks like we'll get this for free in contour 1.11
https://github.com/projectcontour/contour/issues/2777#issuecomment-756424691
