### ISSUE TITLE
scale test flakes

### ISSUE THREAD

**Issue by mattmoor** [knative-sandbox/net-contour#308]
Three flakes today:
https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-serving-contour-latest/1314486816950194177
https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-serving-contour-latest/1314607485239169025
https://prow.knative.dev/view/gcs/knative-prow/logs/ci-knative-serving-contour-latest/1314668010316763136

Note that Contour 1.9.0 landed yesterday (morning): https://github.com/knative/serving/pull/9733, which seems like the main variable.

Here is the failure message (for all three):

```
scale.go:192: WaitForEndpointState(expected text) = response: status: 200, body: Hello World! How about some tasty noodles?
        , headers: map[Content-Type:[text/plain; charset=utf-8] Date:[Fri, 09 Oct 2020 09:28:57 GMT] Server:[envoy] Vary:[Accept-Encoding] X-Envoy-Upstream-Service-Time:[4883] Zipkin_trace_id:[ce90c11f0499856fd55819f1b09fea9e]] did not pass checks: context deadline exceeded
```

Here's the testgrid I generally monitor: https://testgrid.knative.dev/serving#contour-latest&width=20&exclude-non-failed-tests=100&sort-by-flakiness=100

cc @dprotaso @stevesloka @jpeach

**Comment by stevesloka** [comment]
Hey @mattmoor, are you still seeing these failures in your tests? Just wanted to follow up on this.

**Comment by mattmoor** [comment]
I would say that failure rates are higher than they were, but not as high as that initial burst.

Looking at the net-contour dashboard I see a couple failures in a recent run: https://testgrid.knative.dev/net-contour#continuous&exclude-non-failed-tests=100&sort-by-flakiness=100&width=20

**Comment by mattmoor** [comment]
It is sorta back with a vengeance the last few days 😞
