### ISSUE TITLE
Usage of RBAC:v1beta1

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/net-contour#345]
Noticing usage of deprecated `RBAC:v1beta1` APIS:

```
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
```

* https://github.com/knative-sandbox/net-contour/blob/master/config/contour/external.yaml#L1
* https://github.com/knative-sandbox/net-contour/blob/master/config/contour/internal.yaml#L1

**Comment by mattmoor** [comment]
I think this was fixed in Contour 1.10
