### ISSUE TITLE
Ability to set custom fields on generate HTTPProxy specs

### ISSUE THREAD

**Issue by johanbrandhorst** [knative-sandbox/net-contour#347]
Hi, great work on the project. I'm been playing around with it in my local cluster and I'm wondering if there is any way that I can configure the generated HTTPProxies? For example, to set an `ExtensionService` or to configure `CORS` settings for the proxy. Could this be exposed via the `config-contour` somehow?

**Comment by dprotaso** [comment]
Hey sorry missed this - I think what would be the _best_ scenario is if net-contour could be good citizen with a cooperating webhook that can set these additional properties on create/update. I think now the controller would reconcile any changes away.


This sorta becomes a larger issue cause we'd want something like this in our controller framework so it would work across the board.

**Comment by dprotaso** [comment]
Made the tracking issue issue for this as a general problem.

If you have specific things you're looking to configure it may make sense to create separate issues.

ie. HTTP Auth - https://github.com/knative-sandbox/net-contour/issues/491

**Comment by johanbrandhorst** [comment]
OK, makes sense!
