### ISSUE TITLE
Investigate whether contour-operator helps with deploying Contour

### ISSUE THREAD

**Issue by jpeach** [knative-sandbox/net-contour#385]
The https://github.com/projectcontour/contour-operator repo has a Contour operator that can deploy instances of Contour in different configurations. It might be worth taking a look at whether this can be used for deploying Contour in a Knative configuration

**Comment by jpeach** [comment]
cc @daneyon

**Comment by nak3** [comment]
We should start using operator now as it manages Gateway and GatewayClass on gateway API (Ingress v2).

https://projectcontour.io/guides/gateway-api/

> The preferred method for using Gateway API is with Contour Operator. This is because the GatewayClass and Gateway resources should be managed by active controllers that are implemented by the operator.

**Comment by nak3** [comment]
Knative uses two separated ingress internal and external. And it seems there is no supported way to specify `--ingress-class-name` for operator. 
Luckily https://github.com/projectcontour/contour-operator/issues/228 was opened just today.
