### ISSUE TITLE
Update to 1.12

### ISSUE THREAD

**Issue by mattmoor** [knative-sandbox/net-contour#389]
https://github.com/projectcontour/contour/releases/tag/v1.11.0

**Comment by dprotaso** [comment]
Fixes: https://github.com/knative-sandbox/net-contour/issues/188

**Comment by mattmoor** [comment]
I believe that Dave's update to 1.19 libs should unblock this.

**Comment by mattmoor** [comment]
hmm, nevermind we're still on 1.18 libs here 😞

**Comment by mattmoor** [comment]
Related: https://github.com/knative-sandbox/net-contour/pull/412

**Comment by mattmoor** [comment]
1.11 seems to have broken DomainMapping 😞

**Comment by mattmoor** [comment]
Sounds like 1.12 is landing later today and seems to work w/ HEAD
