### ISSUE TITLE
Probing always fails when HTTP fallback is disabled in config-network

### ISSUE THREAD

**Issue by dprotaso** [knative-sandbox/net-contour#423]
When HTTP fallback is disabled probing will set an `https` scheme and a port of `443`

https://github.com/knative-sandbox/net-contour/blob/50b263c04bb6ff46398f9a2baa06cd9f13cc0ba3/pkg/reconciler/contour/lister.go#L48-L52

Contour targets Pod IPs for probing which doesn't do TLS termination so the endpoints will never be ready.

**Comment by nak3** [comment]
/assign

I will work on this.

**Comment by dprotaso** [comment]
Note this issue changes slightly when https://github.com/knative-sandbox/net-contour/pull/610 lands

Since we'll want to configure the spec.HTTPOption now

**Comment by kvmware** [comment]
When using `kubectl apply -f https://github.com/knative/net-contour/releases/download/v0.25.0/contour.yaml` and `kubectl apply -f https://github.com/knative/net-contour/releases/download/v0.25.0/net-contour.yaml` a service is created `kn service create hello --image gcr.io/knative-samples/helloworld-go --port 8080 --env TARGET=New_World --revision-name=new_world` which results in:

**`$ kubectl get ksvc`**
```
NAME    URL                                           LATESTCREATED   LATESTREADY   READY     REASON
hello   https://hello.default.34.71.36.176.sslip.io   hello-world     hello-world   Unknown   EndpointsNotReady
```

**`$ kubectl describe ksvc hello`**
```
...
Status:
  Address:
    URL:  http://hello.default.svc.cluster.local
  Conditions:
    Last Transition Time:        2021-09-23T19:05:43Z
    Status:                      True
    Type:                        ConfigurationsReady
    Last Transition Time:        2021-09-23T19:05:44Z
    Message:                     Waiting for Envoys to receive Endpoints data.
    Reason:                      EndpointsNotReady
    Status:                      Unknown
    Type:                        Ready
    Last Transition Time:        2021-09-23T19:05:44Z
    Message:                     Waiting for Envoys to receive Endpoints data.
    Reason:                      EndpointsNotReady
    Status:                      Unknown
    Type:                        RoutesReady
  Latest Created Revision Name:  hello-world
  Latest Ready Revision Name:    hello-world
  Observed Generation:           1
  Traffic:
    Latest Revision:  true
    Percent:          100
    Revision Name:    hello-world
  URL:                https://hello.default.34.71.36.176.sslip.io
...
```

Changing this to use `kubectl apply -f https://github.com/knative/net-contour/releases/download/v0.26.0/contour.yaml` and `kubectl apply -f https://github.com/knative/net-contour/releases/download/v0.26.0/net-contour.yaml` which includes the changes from #610 the result is thus:

**`$ kubectl get ksvc`**
```
NAME    URL                                           LATESTCREATED   LATESTREADY   READY     REASON
hello   https://hello.default.34.71.36.176.sslip.io   hello-world     hello-world   True
```

**`$ kubectl describe ksvc hello`**
```
...
Status:
  Address:
    URL:  http://hello.default.svc.cluster.local
  Conditions:
    Last Transition Time:        2021-09-23T19:05:43Z
    Status:                      True
    Type:                        ConfigurationsReady
    Last Transition Time:        2021-09-23T19:24:51Z
    Status:                      True
    Type:                        Ready
    Last Transition Time:        2021-09-23T19:24:51Z
    Status:                      True
    Type:                        RoutesReady
  Latest Created Revision Name:  hello-world
  Latest Ready Revision Name:    hello-world
  Observed Generation:           1
  Traffic:
    Latest Revision:  true
    Percent:          100
    Revision Name:    hello-world
  URL:                https://hello.default.34.71.36.176.sslip.io
...
```

**`$ curl https://hello.default.34.71.36.176.sslip.io`**
```
Hello World!
```

**Comment by nak3** [comment]
Yes, I believe https://github.com/knative-sandbox/net-contour/pull/610 solved this issue as well. @kvmware Thank you for the confirmation. And I'm sorry if you wanted to tackle this issue :cold_sweat:
