### ISSUE TITLE
e2e Contour probing continues after resources are deleted

### ISSUE THREAD

**Issue by evankanderson** [knative-sandbox/net-contour#456]
From https://github.com/knative/serving/issues/10943

@shinigambit

# What version of Knative?
0.21

# Expected Behavior
Even after e2e tests timeout, probing for deleted resources stops

# Actual Behavior
After a timeout running the e2e tests, about every 30 seconds log output appears about the contour-ingress-controller failing probes for a service in the serving-tests namespace:
```
knative-serving/contour-ingress-controller-79c8fd5bb9-xz7q4[controller]:
  {
    "severity":"ERROR",
	"timestamp":"2021-03-11T15:30:47.568845788Z",
	"logger":"contour-ingress-controller.knative.dev-net-contour-pkg-reconciler-contour.Reconciler",
	"caller":"status/status.go:398",
	"message":"Probing of http://rollback-b-y-o-name-enibfvlt-byo-foo-new.gen-2.rollback-b-y-o-name-enibfvlt.serving-tests.net-contour.invalid failed, IP: 10.0.4.2:80,ready: false, error: unexpected status code: want 200, got 404 (depth: 0)","commit":"0df7ed8","knative.dev/traceid":"4be4d62a-09e7-4365-9f6b-6ee2cf34ba0b","knative.dev/key":"serving-tests/rollback-b-y-o-name-enibfvlt--ep","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"knative.dev/networking@v0.0.0-20210107024535-ecb89ced52d9/pkg/status/status.go","line":"398","function":"knative.dev/networking/pkg/status.(*Prober).processWorkItem"},
	"stacktrace":"knative.dev/networking/pkg/status.(*Prober).processWorkItem\n\tknative.dev/networking@v0.0.0-20210107024535-ecb89ced52d9/pkg/status/status.go:398\nknative.dev/networking/pkg/status.(*Prober).Start.func1\n\tknative.dev/networking@v0.0.0-20210107024535-ecb89ced52d9/pkg/status/status.go:288"
  }
```

# Steps to Reproduce the Problem
* run all e2e `go test -race -count=1 -timeout=10m -tags=e2e ./test/e2e --ingressendpoint=SOME_IP --enable-alpha` tests with a small timeout (like 10 minutes)
* e2e tests timeout
* log output indicates a controller still is doing probes for a deleted service in serving-tests namespace
* look for services in that namespace and see that there's none
* delete serving-tests namespace to ensure everything gets deleted
* probing output continues hours after

**Comment by evankanderson** [comment]
@shinigambit also reported: 

> Based on the name of the service being probed I assume the issue is mainly in the `TestRollbackBYOName` test in `rollback_byo_test.go` this is currently happening in my GKE instance and I can't think of a way to fix it other than recreating the whole cluster, I'll try to reproduce it in a more consistent way locally @nak3

**Comment by evankanderson** [comment]
If you down the net-contour controller, does the error go away?

**Comment by shinigambit** [comment]
I ended up recreating the cluster but I'm trying to reproduce the issue so I can add more specific steps to reproduce, then I'll be able to check if downing the net-countour controller helps

**Comment by shinigambit** [comment]
tried running all the e2e tests and also the `TestRollbackBYOName` test with different timeouts on a new cluster configured to use contour but couldn't get the same problem to happen, I think this issue can be closed until it can be reproduced consistently
