### ISSUE TITLE
Update Contour

### ISSUE THREAD

**Issue by dprotaso** [knative-sandbox/net-contour#546]
1.17 is due out soon (this week Jul'5th 2021) - we should update as we're on an older version now - 1.14

**Comment by nak3** [comment]
It's ready now https://github.com/projectcontour/contour/releases/tag/v1.17.0 :tada:

**Comment by nak3** [comment]
Ah, contour 1.15+ needs k8s.io lib 0.21+ so it causes dependency confliction

**Comment by dprotaso** [comment]
I guess two options

1. we use require directives to pin to k8s 1.20 libs
2. we use k8s 1.21 libs

I believe this would be the case for just the 0.25 release - I believe 1.19 is EOL in August and we'll move to a new min 1.20 for 0.26

**Comment by xtreme-sameer-vohra** [comment]
Related - https://github.com/knative-sandbox/net-contour/issues/549

**Comment by dprotaso** [comment]
1.17.1 is out because of a CVE

https://twitter.com/projectcontour/status/1418466613251162112

**Comment by kvmware** [comment]
To update to 1.18.1, `enableExternalNameService` is set to `true` and I have disabled the operator from the e2e tests as they don't have a option to configure `enableExternalNameService` yet. I opened an issue for that here https://github.com/projectcontour/contour-operator/issues/437

**Comment by dprotaso** [comment]
PR merged
