### ISSUE TITLE
Resource is not created when the name of the generated HTTPProxy ends with `. `.

### ISSUE THREAD

**Issue by megumish** [knative-sandbox/net-contour#785]
https://github.com/knative-sandbox/net-contour/blob/023772c9c2ed7fae5ac4e47a097a78f76b356744/pkg/reconciler/contour/resources/httpproxy.go#L259

The name of the HTTPProxy is generated here, but kmeta's ChildName() function only takes it into account when the terminator is `-`.

Some hostnames may generate names terminated with `. ` is generated(e.g. `examplefu-external-contour-<hash>examplefu.`) , but the resource is not created because of the resource name rule.

I will fix this by implementing validation in the kmeta code or in the net-contour code. Which do you think is appropriate for the implementation of validation?

**Comment by evankanderson** [comment]
I think https://github.com/knative/pkg/pull/2660 should fix this.

**Comment by dprotaso** [comment]
Update merged.
