### ISSUE TITLE
var substitution failed for 'tlscertificatedelegations.projectcontour.io'

### ISSUE THREAD

**Issue by erltho** [knative-sandbox/net-contour#805]
# Issue

We are trying to install https://github.com/knative/net-contour/releases/download/knative-v1.3.0/contour.yaml when we get following error: 

```bash
reconciliation failed: var substitution failed for 'tlscertificatedelegations.projectcontour.io': YAMLToJSON: yaml: line 81: found unknown escape character
```

## System 

We use fluxCD to kustomize and apply all our k8s/knative config. 

`flux check` gives: 

```bash
✗ flux 0.29.5 <0.32.0 (new version is available, please upgrade)
✔ Kubernetes 1.21.14-eks-18ef993 >=1.20.6-0
✔ helm-controller: deployment ready
► fluxcd/helm-controller:v0.21.0
✔ image-automation-controller: deployment ready
► fluxcd/image-automation-controller:v0.22.1
✔ image-reflector-controller: deployment ready
► fluxcd/image-reflector-controller:v0.18.0
✔ kustomize-controller: deployment ready
► fluxcd/kustomize-controller:v0.25.0
✔ notification-controller: deployment ready
► fluxcd/notification-controller:v0.23.5
✔ source-controller: deployment ready
► fluxcd/source-controller:v0.24.4
✔ all checks passed
```

If we manually apply the configuration with `k apply -f https://github.com/knative/net-contour/releases/download/knative-v1.3.0/contour.yaml` it seems to work. 

## Suggested solution

Adding support for fluxCD. 

We are quite blank on this, spent couple of days, but did not find a workaround yet.

**Comment by dprotaso** [comment]
> If we manually apply the configuration with k apply -f https://github.com/knative/net-contour/releases/download/knative-v1.3.0/contour.yaml it seems to work.

Seems like FluxCD or kustomize is mangling something and it's worth opening and issue with those tools.
